server:
  port: 8081
  servlet:
     context-path: /v1
spring:
   mail:
    host: smtp.gmail.com
    username: yourgmail@mail.com   
    password: XXXXXXXX
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
   jpa:
      show-sql : false
      hibernate:
           ddl-auto: update
   datasource:
      url: jdbc:mysql://localhost:3306/cqs
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: root@123
      
swagger:
   local-url: http://localhost:8081
